### ISSUE TITLE
Decompiled files from original Wooden Furniture mod

### ISSUE THREAD

**Issue by BaalEvan** [pether-pg/ONI_Mods_byRonivan#1]
Hi!
I found an old copy of Wooden furniture mod on my hard drive, and based on your comments on Steam, you might find it helpful.
I uploaded it here, but based on how the files look like you recreated everything from scratch, so maybe animation/png files will be helpful for you :)
https://github.com/BaalEvan/ONI_Mods_byRonivan/tree/main/WoodenSetFurniture

I should have more of Ronivan mods downloaded, just in case.

**Comment by pether-pg** [comment]
Thanks! That will be indeed very helpful!

**Comment by pether-pg** [comment]
Released update with missing furniture, thanks for the help!
